import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={` ${roboto.variable} antialiased`}
      >

      <Provider>
        {children}
      </Provider>

      </body>
    </html>
  </ClerkProvider>
  );
}
